"""
This file is not part of the source code. For ease of development, this repo
can be placed directly inside the Anki addons directory, and the latest source
code will be loaded whenever Anki is opened.

The __init__.py included in the final .ankiaddon file is generated by 
build_for_release.sh.
"""

from .src import insert_symbols
