# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/Ui_SymbolWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SymbolWindow(object):
    def setupUi(self, SymbolWindow):
        SymbolWindow.setObjectName("SymbolWindow")
        SymbolWindow.resize(500, 450)
        SymbolWindow.setMinimumSize(QtCore.QSize(500, 450))
        SymbolWindow.setMaximumSize(QtCore.QSize(500, 450))
        SymbolWindow.setAcceptDrops(False)
        SymbolWindow.setAutoFillBackground(False)
        self.verticalLayoutWidget = QtWidgets.QWidget(SymbolWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 501, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 15)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.keyLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.keyLineEdit.setFont(font)
        self.keyLineEdit.setText("")
        self.keyLineEdit.setObjectName("keyLineEdit")
        self.gridLayout_2.addWidget(self.keyLineEdit, 1, 1, 1, 1)
        self.valueLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.valueLineEdit.setFont(font)
        self.valueLineEdit.setObjectName("valueLineEdit")
        self.gridLayout_2.addWidget(self.valueLineEdit, 1, 2, 1, 1)
        self.labelWith = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelWith.setObjectName("labelWith")
        self.gridLayout_2.addWidget(self.labelWith, 0, 2, 1, 1)
        self.labelReplace = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelReplace.setObjectName("labelReplace")
        self.gridLayout_2.addWidget(self.labelReplace, 0, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setMidLineWidth(0)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setTabKeyNavigation(False)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setRowCount(2)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(190)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.tableWidget, 2, 1, 1, 2)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelBlank = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelBlank.setText("")
        self.labelBlank.setObjectName("labelBlank")
        self.verticalLayout_2.addWidget(self.labelBlank)
        self.addReplaceButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addReplaceButton.sizePolicy().hasHeightForWidth())
        self.addReplaceButton.setSizePolicy(sizePolicy)
        self.addReplaceButton.setMaximumSize(QtCore.QSize(244, 16777215))
        self.addReplaceButton.setObjectName("addReplaceButton")
        self.verticalLayout_2.addWidget(self.addReplaceButton)
        self.deleteButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout_2.addWidget(self.deleteButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.importButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.importButton.setObjectName("importButton")
        self.horizontalLayout_2.addWidget(self.importButton)
        self.exportButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout_2.addWidget(self.exportButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.okButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_2.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.resetButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_2.addWidget(self.resetButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SymbolWindow)
        QtCore.QMetaObject.connectSlotsByName(SymbolWindow)

    def retranslateUi(self, SymbolWindow):
        _translate = QtCore.QCoreApplication.translate
        SymbolWindow.setWindowTitle(_translate("SymbolWindow", "Insert Symbol Options"))
        self.labelWith.setText(_translate("SymbolWindow", "With"))
        self.labelReplace.setText(_translate("SymbolWindow", "Replace"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("SymbolWindow", "key1"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("SymbolWindow", "value1"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("SymbolWindow", "key2"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("SymbolWindow", "value2"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.addReplaceButton.setText(_translate("SymbolWindow", "Add"))
        self.deleteButton.setText(_translate("SymbolWindow", "Delete"))
        self.importButton.setText(_translate("SymbolWindow", "Import"))
        self.exportButton.setText(_translate("SymbolWindow", "Export"))
        self.okButton.setText(_translate("SymbolWindow", "OK"))
        self.cancelButton.setText(_translate("SymbolWindow", "Cancel"))
        self.resetButton.setText(_translate("SymbolWindow", "Reset"))

